---
- name: Pre-Checks and Installations
  hosts: localhost
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    git_command: git --version
    maven_command: mvn --version
    kubectl_command: kubectl version --client
    sonar_url: http://10.138.77.104:9000
    docker_registry_url: https://hub.docker.com/u/bhavanaguda
  tasks:
    - name: Check if Git is installed
      command: "{{ git_command }}"
      register: git_result
      ignore_errors: yes
    - name: Git is not installed
      debug:
        msg: Git is not installed.
      when: git_result is failed
    - name: Check if Maven is installed
      command: "{{ maven_command }}"
      register: maven_result
      ignore_errors: yes
    - name: Maven is not installed
      debug:
        msg: Maven is not installed.
      when: maven_result is failed
    - name: Check if Kubernetes is installed
      command: "{{ kubectl_command }}"
      register: kubectl_result
      ignore_errors: yes
    - name: Kubernetes is not installed
      debug:
        msg: Kubernetes is not installed.
      when: kubectl_result is failed
    - name: Update apt cache
      apt:
        update_cache: yes
      when: git_result is failed or maven_result is failed
    - name: Install Git
      apt:
        name: git
        state: present
      when: git_result is failed
    - name: Install Maven
      apt:
        name: maven
        state: present
      when: maven_result is failed
    - name: Install Kubernetes
      shell: >
        curl -LO
        "https://storage.googleapis.com/kubernetes-release/release/$(curl -s
        https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        &&

        chmod +x ./kubectl &&

        mv ./kubectl /usr/local/bin/kubectl
      when: kubectl_result is failed
    - name: Check if SonarQube is reachable
      uri:
        url: "{{ sonar_url }}"
        return_content: yes
        status_code: 200
      register: sonar_result
      ignore_errors: yes
    - name: SonarQube is not reachable
      debug:
        msg: SonarQube is not reachable.
      when: sonar_result.status != 200
    - name: Check if Docker Registry is reachable
      uri:
        url: "{{ docker_registry_url }}"
        return_content: yes
        status_code: 200
      register: docker_result
      ignore_errors: yes
    - name: Docker Registry is not reachable
      debug:
        msg: Docker Registry is not reachable.
      when: docker_result.status != 200
