---
- name: CI/CD Pre-Checks
  hosts: localhost
  tasks:
    - name: Check GitLab
      uri:
        url: https://github.com/bhavanaguda
        status_code: 200
      register: gitlab_response
      ignore_errors: yes
    - name: Check Maven
      shell: mvn --version
      register: maven_response
      ignore_errors: yes
    - name: Check SonarQube
      uri:
        url: http://10.138.77.104:9000
        status_code: 200
      register: sonarqube_response
      ignore_errors: yes
    - name: Check Docker Registry
      uri:
        url: https://hub.docker.com/u/bhavanaguda
        status_code: 200
      register: docker_registry_response
      ignore_errors: yes
    - name: Check Kubernetes node status
      shell: kubectl get nodes
      register: kubernetes_node_status
      ignore_errors: yes
    - name: Display Results
      debug:
        msg: |
          GitLab: {{ gitlab_response.status }}
          Maven: {{ maven_response.rc }}
          SonarQube: {{ sonarqube_response.status }}
          Docker Registry: {{ docker_registry_response.status }}
          Kubernetes: {{ kubernetes_response.rc }}
