---
- name: CI/CD Pre-Checks
  hosts: localhost
  tasks:
    - name: Check GitLab
      uri:
        url: http://gitlab.example.com
        status_code: 200
      register: gitlab_response
      ignore_errors: yes
    - name: Check Maven
      shell: mvn --version
      register: maven_response
      ignore_errors: yes
    - name: Check SonarQube
      uri:
        url: http://sonarqube.example.com
        status_code: 200
      register: sonarqube_response
      ignore_errors: yes
    - name: Check Docker Registry
      uri:
        url: http://docker-registry.example.com/v2/
        status_code: 200
      register: docker_registry_response
      ignore_errors: yes
    - name: Check Kubernetes
      shell: kubectl cluster-info dump
      register: kubernetes_response
      ignore_errors: yes
    - name: Display Results
      debug:
        msg: |
          GitLab: {{ gitlab_response.status }}
          Maven: {{ maven_response.rc }}
          SonarQube: {{ sonarqube_response.status }}
          Docker Registry: {{ docker_registry_response.status }}
          Kubernetes: {{ kubernetes_response.rc }}
