---
- name: CI/CD Pre-Checks
  hosts: localhost
  tasks:
    - name: Check GitLab
      uri:
        url: https://github.com/bhavanaguda
        status_code: 200
      register: gitlab_response
      ignore_errors: yes
    - name: Check Git
      shell: git --version
      register: git_response
      ignore_errors: yes
      failed_when: "'git' not in git_response.stdout"
      no_log: true
    - name: Check Maven
      shell: mvn --version
      register: maven_response
      ignore_errors: yes
      failed_when: "'mvn' not in maven_response.stdout"
      no_log: true      
    - name: Check SonarQube
      uri:
        url: http://10.138.77.106:9000
        status_code: 200
      register: sonarqube_response
      ignore_errors: yes
    - name: Check Docker
      shell: docker --version
      register: docker_response
      ignore_errors: yes
      failed_when: "'docker' not in docker_response.stdout"
      no_log: true
    - name: Check Docker Registry
      uri:
        url: https://hub.docker.com/u/bhavanaguda
        status_code: 200
      register: docker_registry_response
      ignore_errors: yes
    - name: Check Kubernetes
      shell: kubectl cluster-info
      register: kubernetes_response
      ignore_errors: yes
      failed_when: "'kubectl' not in kubernetes_response.stderr"
      no_log: true
    - name: Display Results
      debug:
        msg: >
          GitLab: {{ gitlab_response.status }}
          Git: {{ 'installed' if 'git' in git_response.stdout else 'not installed' }}
          Maven: {{ 'installed' if 'mvn' in maven_response.stdout else 'not installed' }}
          SonarQube: {{ sonarqube_response.status }}
          Docker: {{ 'installed' if 'docker' in docker_response.stdout else 'not installed' }}
          Docker Registry: {{ docker_registry_response.status }}
          Kubernetes: {{ 'installed' if 'kubectl' in kubernetes_response.stderr else 'not installed' }}
      
