---
- name: CI/CD Pre-Checks
  hosts: localhost
  tasks:
    - name: Check GitLab
      uri:
        url: https://github.com/bhavanaguda
        status_code: 200
      register: gitlab_response
      ignore_errors: yes
 
    - name: Check Git
      shell: git --version > git_version_check.txt 2>&1
      args:
        creates: git_version_check.txt
      register: git_response
 
    - name: Check Maven
      shell: mvn --version > mvn_version_check.txt 2>&1
      args:
        creates: mvn_version_check.txt
      register: maven_response
 
    - name: Check SonarQube
      uri:
        url: http://10.138.77.106:9000
        status_code: 200
      register: sonarqube_response
      ignore_errors: yes
 
    - name: Check Docker
      shell: docker --version > docker_version_check.txt 2>&1
      args:
        creates: docker_version_check.txt
      register: docker_response
 
    - name: Check Docker Registry
      uri:
        url: https://hub.docker.com/u/bhavanaguda
        status_code: 200
      register: docker_registry_response
      ignore_errors: yes
 
    - name: Check Kubernetes
      shell: kubectl cluster-info > kubectl_check.txt 2>&1
      args:
        creates: kubectl_check.txt
      register: kubernetes_response
 
    - name: Display Results
      debug:
        msg: |
          GitLab: {{ gitlab_response.status }}
          Git: {{ 'installed' if 'git' in lookup('file', 'git_version_check.txt') else 'not installed' }}
          Maven: {{ 'installed' if 'Apache Maven' in lookup('file', 'mvn_version_check.txt') else 'not installed' }}
          SonarQube: {{ sonarqube_response.status }}
          Docker: {{ 'installed' if 'Docker version' in lookup('file', 'docker_version_check.txt') else 'not installed' }}
          Docker Registry: {{ docker_registry_response.status }}
          Kubernetes: {{ 'installed' if 'Kubernetes master' in lookup('file', 'kubectl_check.txt') else 'not installed' }}

