---
- name: CI/CD Pre-Checks
  hosts: localhost
  tasks:
    - name: Check Git
      command: which git
      register: git_command_output
      ignore_errors: true
 
    - name: Check Maven
      command: which mvn
      register: maven_command_output
      ignore_errors: true
 
    - name: Check SonarQube
      uri:
      url: http://10.138.77.104:9000
      status_code: 200
      register: sonarqube_response
      ignore_errors: true
 
    - name: Check Docker
      command: which docker
      register: docker_command_output
      ignore_errors: true
 
    - name: Check Docker Registry
      uri:
       url: https://hub.docker.com/u/bhavanaguda
       status_code: 200
      register: docker_registry_response
      ignore_errors: true
 
    - name: Check Kubernetes
      command: which kubectl
      register: kubectl_command_output
      ignore_errors: true
 
    - block:
        - fail:
            msg: "Git is not installed"
          when: git_command_output.rc != 0
        - debug:
            msg: "Git is installed"
          when: git_command_output.rc == 0
 
        - fail:
            msg: "Maven is not installed"
          when: maven_command_output.rc != 0
        - debug:
            msg: "Maven is installed"
          when: maven_command_output.rc == 0
 
        - fail:
            msg: "SonarQube is not available"
          when: sonarqube_response.status != 200
        - debug:
            msg: "SonarQube is available"
          when: sonarqube_response.status == 200
 
        - fail:
            msg: "Docker is not installed"
          when: docker_command_output.rc != 0
        - debug:
            msg: "Docker is installed"
          when: docker_command_output.rc == 0
 
        - fail:
            msg: "Docker Registry is not available"
          when: docker_registry_response.status != 200
        - debug:
            msg: "Docker Registry is available"
          when: docker_registry_response.status == 200
 
        - fail:
            msg: "Kubernetes is not installed"
          when: kubectl_command_output.rc != 0
        - debug:
            msg: "Kubernetes is installed"
          when: kubectl_command_output.rc == 0
 
      rescue:
        - debug:
            msg: "An error occurred during pre-checks. Please review the logs for more information."
