---
- name: Pre-Checks for CI/CD Pipeline
  hosts: localhost
  tasks:
    - name: Check if GitLab is reachable
      uri:
        url: https://github.com/bhavanaguda
        status_code: 200
      register: gitlab_status
    - name: Check if Maven is installed
      command: mvn --version
      register: maven_status
      ignore_errors: yes
    - name: Check if SonarQube is reachable
      uri:
        url: http://10.138.77.106:9000
        status_code: 200
      register: sonarqube_status
    - name: Check if Docker Registry is reachable
      uri:
        url: https://hub.docker.com/u/bhavanaguda
        status_code: 200
      register: docker_registry_status
    - name: Check if Kubernetes is reachable
      command: kubectl --insecure-skip-tls-verify cluster-info dump
      register: kubernetes_status
      ignore_errors: yes
    - name: Display pre-checks results
      debug:
        msg: >
          GitLab: {{ gitlab_status.status }},
          Maven: {{ "Installed" if maven_status.rc == 0 else "Not Installed" }},
          SonarQube: {{ sonarqube_status.status }},
          Docker Registry: {{ docker_registry_status.status }},
          Kubernetes: {{ "Running" if kubernetes_status.rc == 0 else "Not Running" }}
