---
- name: CI/CD Pre-Checks
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if Git is installed
      command: which git
      register: git_check
      ignore_errors: true
 
    - name: Check if Git is reachable
  command: git ls-remote --exit-code https://gitlab.example.com/project.git HEAD
  register: git_reachable
  ignore_errors: true
 
 
- name: Display Results
  debug:
      msg: |
          Git:
            {% if git_check.rc == 0 %}
              {% if git_reachable.rc == 0 %}
                installed and reachable
              {% else %}
                installed but not reachable
              {% endif %}
            {% else %}
              not installed
            {% endif %}
