---
- name: Pre-Checks for CI/CD Pipeline
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check GitLab
      uri:
url: https://github.com/bhavanaguda/Ansible/
        method: GET
      register: gitlab_check
      ignore_errors: yes
 
    - name: Check Maven
      shell: mvn --version
      register: maven_check
      ignore_errors: yes
 
    - name: Check SonarQube
      uri:
url: http://10.138.77.104:9000
        method: GET
      register: sonarqube_check
      ignore_errors: yes
 
    - name: Check Docker Registry
      uri:
url: https://hub.docker.com/u/bhavanaguda
        method: GET
      register: docker_registry_check
      ignore_errors: yes
 
    - name: Check Kubernetes
      shell: kubectl version
      register: kubernetes_check
      ignore_errors: yes
 
    - name: Print Results
      debug:
        msg: "GitLab: {{ 'OK' if gitlab_check.status == 200 else 'Not Reachable' }}, Maven: {{ 'OK' if maven_check.rc == 0 else 'Not Installed' }}, SonarQube: {{ 'OK' if sonarqube_check.status == 200 else 'Not Reachable' }}, Docker Registry: {{ 'OK' if docker_registry_check.status == 200 else 'Not Reachable' }}, Kubernetes: {{ 'OK' if kubernetes_check.rc == 0 else 'Not Installed' }}"
has context menu
