---
- name: CI/CD Pre-Checks
  hosts: localhost
  tasks:
    - block:
        - name: Check GitLab
          uri:
            url: https://github.com/bhavanaguda
            status_code: 200
          register: gitlab_response
 
        - name: Check Git
          command: git --version
          register: git_response
          ignore_errors: yes
 
        - name: Check Maven
          command: mvn --version
          register: maven_response
          ignore_errors: yes
 
        - name: Check SonarQube
          uri:
            url: http://10.138.77.106:9000
            status_code: 200
          register: sonarqube_response
 
        - name: Check Docker
          command: docker --version
          register: docker_response
          ignore_errors: yes
 
        - name: Check Docker Registry
          uri:
            url: https://hub.docker.com/u/bhavanaguda
            status_code: 200
          register: docker_registry_response
 
        - name: Check Kubernetes
          shell: kubectl cluster-info
          register: kubernetes_response
          ignore_errors: yes
 
        - name: Display Results
          debug:
            msg: |
              GitLab: {{ gitlab_response.status }}
              Git: {{ 'installed' if git_response is defined and 'git' in git_response.stdout else 'not installed' }}
              Maven: {{ 'installed' if maven_response is defined and 'Apache Maven' in maven_response.stdout else 'not installed' }}
              SonarQube: {{ sonarqube_response.status }}
              Docker: {{ 'installed' if docker_response is defined and 'Docker version' in docker_response.stdout else 'not installed' }}
              Docker Registry: {{ docker_registry_response.status }}
              Kubernetes: {{ 'installed' if kubernetes_response is defined and 'Kubernetes master' in kubernetes_response.stderr else 'not installed' }}

